// Created by iWeb 3.0.4 local-build-20140701

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,355),url:'Dans_Web_Pages_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Dans_Web_Pages_files/stroke_1.png'},{rect:new IWRect(3,-3,285,6),url:'Dans_Web_Pages_files/stroke_2.png'},{rect:new IWRect(288,-3,6,6),url:'Dans_Web_Pages_files/stroke_3.png'},{rect:new IWRect(288,3,6,355),url:'Dans_Web_Pages_files/stroke_4.png'},{rect:new IWRect(288,358,6,6),url:'Dans_Web_Pages_files/stroke_5.png'},{rect:new IWRect(3,358,285,6),url:'Dans_Web_Pages_files/stroke_6.png'},{rect:new IWRect(-3,358,6,6),url:'Dans_Web_Pages_files/stroke_7.png'}],new IWSize(291,361)),reflection_1:new IWReflection({opacity:0.33,offset:1.00}),reflection_0:new IWReflection({opacity:0.50,offset:1.00}),reflection_3:new IWReflection({opacity:0.65,offset:1.00}),reflection_2:new IWReflection({opacity:0.33,offset:1.00}),stroke_1:new IWStrokeParts([{rect:new IWRect(-18,7,28,1071),url:'Dans_Web_Pages_files/stroke_8.png'},{rect:new IWRect(-18,-10,28,17),url:'Dans_Web_Pages_files/stroke_9.png'},{rect:new IWRect(10,-10,317,17),url:'Dans_Web_Pages_files/stroke_10.png'},{rect:new IWRect(327,-11,33,18),url:'Dans_Web_Pages_files/stroke_11.png'},{rect:new IWRect(327,7,31,1071),url:'Dans_Web_Pages_files/stroke_12.png'},{rect:new IWRect(327,1078,28,24),url:'Dans_Web_Pages_files/stroke_13.png'},{rect:new IWRect(10,1078,317,28),url:'Dans_Web_Pages_files/stroke_14.png'},{rect:new IWRect(-13,1078,23,23),url:'Dans_Web_Pages_files/stroke_15.png'}],new IWSize(344,1088))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Dans_Web_Pages_files/Dans_Web_PagesMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');IMpreload('Dans_Web_Pages_files','shapeimage_8','0');IMpreload('Dans_Web_Pages_files','shapeimage_8','1');IMpreload('Dans_Web_Pages_files','shapeimage_8','2');IMpreload('Dans_Web_Pages_files','shapeimage_8','3');IMpreload('Dans_Web_Pages_files','shapeimage_8','4');IMpreload('Dans_Web_Pages_files','shapeimage_8','5');IMpreload('Dans_Web_Pages_files','shapeimage_8','6');IMpreload('Dans_Web_Pages_files','shapeimage_8','7');fixupIECSS3Opacity('id5');applyEffects()}
function onPageUnload()
{Widget.onunload();}
